spring:
  application:
    name: admin-service #微服务名称
  config:
    import: nacos:admin-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.14.138:8848  # nacos地址
      config:
        server-addr: 117.72.14.138:8848  # nacos地址
        file-extension: yml